/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './App.tsx'],
  theme: {
    extend: {
      colors: {
        mira: {
          primary: '#6366f1',
          'primary-dark': '#4f46e5',
          success: '#22c55e',
          warning: '#f59e0b',
          danger: '#ef4444',
          'danger-light': '#fca5a5',
          muted: '#9ca3af',
          'bg-base': '#ffffff',
          'bg-subtle': '#f9f9f9',
          'bg-input': '#f5f5f5',
          'bg-bubble': '#f0f0f0',
          'text-base': '#111111',
          'text-secondary': '#333333',
          'text-tertiary': '#666666',
          'text-muted': '#888888',
          'text-placeholder': '#999999',
          border: '#e0e0e0',
          'border-light': '#e8e8e8',
          hint: '#eef2ff',
          'hint-text': '#4f46e5',
          banner: '#fef3c7',
          'banner-text': '#92400e',
        },
      },
      borderRadius: {
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '14px',
        'mira-xl': '16px',
        'mira-full': '20px',
      },
      fontSize: {
        'mira-xs': ['12px', { lineHeight: '16px' }],
        'mira-sm': ['13px', { lineHeight: '20px' }],
        'mira-base': ['14px', { lineHeight: '22px' }],
        'mira-md': ['15px', { lineHeight: '22px' }],
        'mira-lg': ['16px', { lineHeight: '24px' }],
        'mira-xl': ['17px', { lineHeight: '24px' }],
        'mira-2xl': ['18px', { lineHeight: '28px' }],
        'mira-3xl': ['20px', { lineHeight: '28px' }],
        'mira-4xl': ['28px', { lineHeight: '36px' }],
      },
      spacing: {
        'mira-xs': '4px',
        'mira-sm': '8px',
        'mira-md': '12px',
        'mira-lg': '14px',
        'mira-xl': '16px',
        'mira-2xl': '20px',
        'mira-3xl': '24px',
      },
    },
  },
  plugins: [],
};
